// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlO2aOWeaR5pbADVswJn5c3FG5lMabY4A',
    appId: '1:665434869820:web:1aeb89afedefa2aac8f339',
    messagingSenderId: '665434869820',
    projectId: 'login-provider-46fdd',
    authDomain: 'login-provider-46fdd.firebaseapp.com',
    storageBucket: 'login-provider-46fdd.appspot.com',
    measurementId: 'G-2CD2BN6S7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrVYiRie8hmQKrhiI-pWescwM-Q5zFPew',
    appId: '1:665434869820:android:66efb315a3bde780c8f339',
    messagingSenderId: '665434869820',
    projectId: 'login-provider-46fdd',
    storageBucket: 'login-provider-46fdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASFR7qeu0S8KuIm2YtqLLbasHM_h6r57U',
    appId: '1:665434869820:ios:ce667d2389be167ec8f339',
    messagingSenderId: '665434869820',
    projectId: 'login-provider-46fdd',
    storageBucket: 'login-provider-46fdd.appspot.com',
    iosClientId: '665434869820-anoi9gam3b1q91cr2klutqd0japdn5pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginProvider',
  );
}
